modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "CC0-1"

[[mods]]
modId = "metallics"
version = "${version}"
displayName = "Metallics"
authors = "StellarWind22"
description = '''

'''
logoFile = "logo.png"

[[dependencies.metallics]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.metallics]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.metallics]]
modId = "architectury"
type = "required"
versionRange = "[18.0.6,)"
ordering = "AFTER"
side = "BOTH"
