name: release
on:
  release:
    types:
      - published

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: actions/build
      - name: curseforge-modrinth-publish
        uses: Kir-Antipov/mc-publish@v3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-id-modrinth: "$MODRINTH_ID"
          project-id-curseforge: "$CURSEFORGE_ID"